bookmarks/bookmarks/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls')),
    #the below URL is useful for getting the data of social websites
    url('social-auth/',include('social.apps.django_app.urls', namespace='social')),
	#To redirect to images app
	url(r'^images/',include('images.urls', namespace='images')),
]

#To get in charge of media files during development
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
		url(r'^ranking/$', views.image_ranking, name='ranking'),
        url(r'^create/$',views.image_create,name='create'),
        url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.image_detail, name='detail'),
        url(r'^like/$', views.image_like, name='like'),
        url(r'^$', views.image_list, name='list'),

]

bookmarks/images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.core.urlresolvers import reverse

class Image(models.Model):
        #First argument refers to base class it has refered and name it as images_created
        user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                related_name='images_created')
        title = models.CharField(max_length=200)
        #the field which is used for building URL,letters,numbers,underscore,hyphens are used
        slug = models.SlugField(max_length=200,
                                blank=True)
        url = models.URLField()
        image = models.ImageField(upload_to='images/%Y/%m/%d')
        description = models.TextField(blank=True)
        #db_index=True creates the index in the data base for this field
        created = models.DateField(auto_now_add=True,
                                    db_index=True)
        #A ManyToManyField for number of likes for images by users
        #user likes multiple images
        #Image liked by multiple users
        #Many to many can be achieved like
        #users.images_liked.all() and users.users_like.all()
        users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                            related_name='images_liked',
                                            blank=True)
        #total_likes for a image calculation
        total_likes = models.PositiveIntegerField(db_index=True,default=0)
        def __str__(self):
            return self.title
        #Overiding the base save method to autogenerate save to get slug valye for title
        def save(self, *args, **kwargs):
            if not self.slug:
                self.slug = slugify(self.title)
                #super used here is to get access to the base class methods ex.save here
                super(Image, self).save(*args, **kwargs)
        #the below method is used for building the canonical URLs using the reverse
        def get_absolute_url(self):
                #the first argument is view name
                #second is argument list
                return reverse('images:detail', args=[self.id, self.slug])

bookmarks/images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify
class ImageCreateForm(forms.ModelForm):
    class Meta:
        #To use the model image
        model = Image
        #To use 3 fields from the model
        fields = ('title', 'url', 'description')
        #to make the url to be <hidden> from HTML
        widgets = {
                    'url': forms.HiddenInput,
                    }
    #By default this method is executed when is_valid is invoked
    #Syntax: clean_field_name (here field_name refered to URL)
    def clean_url(self):
        #Get the value for key URL from form
        url = self.cleaned_data['url']
        #Check the valid extensions for jpg or jpeg
        valid_extensions = ['jpg', 'jpeg']
        #Get the extension value through rsplit and convert into lower of that
        extension = url.rsplit('.', 1)[1].lower()
        #Check if its not in valid_extensions to raise a exception
        if extension not in valid_extensions:
                raise forms.ValidationError('The given URL does not ' \
                                            'match valid image extensions.')
        #return the URL
        return url

    def save(self, force_insert=False,
            force_update=False,
            commit=True):
        #to access the save of the base class
        image = super(ImageCreateForm, self).save(commit=False)
        #get the image url
        image_url = self.cleaned_data['url']
        #Formulate the image name
        image_name = '{}.{}'.format(slugify(image.title),
                                            image_url.rsplit('.', 1)[1].lower())
        # download image from the given URL
        response = request.urlopen(image_url)
        #Save the image (acess models image,then image object  of save method )
        #get all details using ContentFile
        image.image.save(image_name,
                        ContentFile(response.read()),
                        save=False)
        #if commit is true use models save
        if commit:
            image.save()
        #return the image
        return image

bookmarks/images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from django.shortcuts import get_object_or_404
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
#get the create_action we have just created
from actions.utils import create_action
#import the redis db
import redis
#import the settings
from django.conf import settings


# connect to redis
r = redis.StrictRedis(host=settings.REDIS_HOST,
                     port=settings.REDIS_PORT,
                     db=settings.REDIS_DB)

@login_required
def image_create(request):
    if request.method == 'POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
                # form data is valid
                cd = form.cleaned_data
                new_item = form.save(commit=False)
                # assign current user to the item
                new_item.user = request.user
                new_item.save()
                #to record the action in the database
                create_action(request.user, 'bookmarked image', new_item)
                messages.success(request, 'Image added successfully')
                # redirect to new created item detail view
                return redirect(new_item.get_absolute_url())
    else:
        # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)
    return render(request,
                 'images/image/create.html',
                 {'section': 'images',
                 'form': form})

def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    # increment total image views by 1
    #to increment value of key
    #Syntax:  object-type(model):id:fieldname (this is overall key)
    total_views = r.incr('image:{}:views'.format(image.id))
    #add total values to dictionary
    # increment image ranking by 1
    #Below is the sorted list
    #syntax (sorted_list_name,key,amount_of_inc_value)
    #increment image_ranking sorted list for the image with given image_id by 1
    r.zincrby('image_ranking', image.id, 1)
    return render(request,
                'images/image/detail.html',
                {'section': 'images',
                'image': image,
                'total_views': total_views})



@ajax_required
@login_required
#To verify that the form method used is POST with the below decorator
@require_POST
def image_like(request):
        #get the values from get parameters
        #iamge_id
        image_id = request.POST.get('id')
        #action
        action   = request.POST.get('action')
        #if both
        if image_id and action:
            try:
                #get image objects using get method
                image = Image.objects.get(id=image_id)
                #if action is like then
                if action == 'like':
                    #users_like is the manager provided by django,use add method
                    image.users_like.add(request.user)
                    #to create a action note that the image is liked/unliked
                    create_action(request.user, 'likes', image)
                else:
                    #use remove method
                    image.users_like.remove(request.user)
                #return JsonResponse if successful
                return JsonResponse({'status':'ok'})
            except:
                pass
        #return JsonResponse if failed
        return JsonResponse({'status':'ko'})


from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, \
                                            PageNotAnInteger
@login_required
def image_list(request):
        #get all the image objects
        images = Image.objects.all()
        #List 8 images for each page
        paginator = Paginator(images, 8)
        #retrieve the page object
        page = request.GET.get('page')
        try:
            #pass the page to get the images
            images = paginator.page(page)
        except PageNotAnInteger:
        # If page is not an integer deliver the first page,example if only 8 images are available secon time display the page 1
            images = paginator.page(1)
        #if page is empty
        except EmptyPage:
            if request.is_ajax():
                # If the request is AJAX and the page is out of range
                # return an empty page
                return HttpResponse('')
            # If page is out of range deliver last page of results
            images = paginator.page(paginator.num_pages)
        if request.is_ajax():
            return render(request,
                        'images/image/list_ajax.html',
                        {'section': 'images', 'images': images})
        return render(request,
                    'images/image/list.html',
                    {'section': 'images', 'images': images})




@login_required
def image_ranking(request):
          # get image ranking dictionary
          #Syntax:r.zrange(sorted_set,start,end,desc:true/false)
          #get all the elements from a sorted set order by desc and slice top 10 elements
          #get the key value pairs
          image_ranking = r.zrange('image_ranking', 0, -1,desc=True)[:10]
          #Build a id set for most viewed
          image_ranking_ids = [int(id) for id in image_ranking]
          # get most viewed images
          most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
          #Here since most_viewed.sort is used most_viewed elements are passed as argument to lambda ,and get the index of those
          #and sort with this as a key
          most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
          return render(request,
                        'images/image/ranking.html',
                        {'section': 'imagesview',
                        'most_viewed': most_viewed})

bookmarks/images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
    <h1>Bookmark an image</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Bookmark it!">
    </form>
{% endblock %}

bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}
<h1>{{ image.title }}</h1>
      <!--loading the image to restrict to certain resolution/size as we come across images in various sizes-->
       <!--thunbernail is the template tag provided by django-->
        {% load thumbnail %}
        <!--once the thunmber nail is loaded it creates image of 300 pixels which will be displayed in the page(that url is refered)-->
        <!--however a hyperlink is provided to get the details-->
        {% thumbnail image.image "300" as im %}
              <a href="{{ image.image.url }}">
                  <img src="{{ im.url }}" class="image-detail">
              </a>
        {% endthumbnail %}
        {% with total_likes=image.users_like.count users_like=image.users_like.all %}
          <div class="image-info">
              <div>
                  <span class="count">
                       <span class="total">{{ total_likes }}</span>like{{ total_likes|pluralize }}
                  </span>
                  <span class="count_2">
                        <span class="total">{{ total_views }}</span>view{{ total_views|pluralize }}
                  </span>
                  <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                      {% if request.user not in users_like %}
                          Like
                      {% else %}
                          Unlike
                      {% endif %}
                  </a>
              </div>
              {{ image.description|linebreaks }}
          </div>
          <div class="image-likes">
              {% for user in image.users_like.all %}
                  <div>
                        <img src="{{ user.profile.photo.url }}">
                        <p>{{ user.first_name }}</p>
                  </div>
              {% empty %}
                    Nobody likes this image yet.
              {% endfor %}
        </div>
      {% endwith %}
{% endblock %}
{% block domready %}
//To select anchor tags with class "like" on clik of its use the below handler
$('a.like').click(function(e){
          //To prevent the default behaviour of anchor tag to navigate to a link
          e.preventDefault();
          //To give the URL reference using iamges:like
          //Below is aynchronus request to the server(pointing to view)
          $.post('{% url "images:like" %}',
          {
              //get the id and action values from anchor place it in POST dictionary
              //These values will be used by view
              id: $(this).data('id'),
              action: $(this).data('action')
          },
          function(data){
                  //Once the data is returned in Json format check if ok
                  if (data['status'] == 'ok')
                  {
                      //select the previously selected action
                      var previous_action = $('a.like').data('action');
                      // toggle data-action
                      $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                      // toggle link text
                      $('a.like').text(previous_action == 'like' ? 'Unlike' :'Like');
                      // update total likes
                      var previous_likes = parseInt($('span.count .total').text());
                      $('span.count .total').text(previous_action == 'like' ?previous_likes + 1 : previous_likes - 1);
                    }
          }
          );
});
{% endblock %}

bookmarks/images/templates/images/image/list.html
{% extends "base.html" %}
{% block title %}Images bookmarked{% endblock %}
{% block content %}
    <h1>Images bookmarked</h1>
    <div id="image-list">
          <!--to include the list_ajax.html template in image list-->
          {% include "images/image/list_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;
    //$(window).scroll is used to capture the scroll event and we define a handler for it
    $(window).scroll(function() {
          //To identify margin available to load next page
          //$(document).height() gives height of entire document
          //$(window).height() gives the height of window
          var margin = $(document).height() - $(window).height() - 200;
          //$(window).scrollTop() gives the position of vertical scrollbar
          if ($(window).scrollTop() > margin && empty_page == false &&block_request == false)
           {
                //initiate next request,hence block any further request
                block_request = true;
                //loading next page hance incrementing the page variable
                page += 1;
                //initiate the ajax request,response gives the data set
                $.get('?page=' + page, function(data) {
                          //If no data set empty_page to true
                          if(data == '') {
                                  empty_page = true;
                                }
                          //If data is already received next request can be initiated hance change block_request = false;
                          //append the current data to image_list(div id mentioned above)
                          else {
                                  block_request = false;
                                  $('#image-list').append(data);
                                }
                      });
          }
});
{% endblock %}

bookmarks/images/templates/images/image/list_ajax.html
{% load thumbnail %}
{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
          {% thumbnail image.image "300x300" crop="100%" as im %}
              <a href="{{ image.get_absolute_url }}">
                <img src="{{ im.url }}">
              </a>
          {% endthumbnail %}
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
                {{ image.title }}
            </a>
       </div>
     </div>
{% endfor %}

bookmarks/images/templates/images/image/ranking.html
{% extends "base.html" %}
{% block title %}Images ranking{% endblock %}
{% block content %}
    <h1>Images ranking</h1>
    <ol>
        {% for image in most_viewed %}
          <li>
              <a href="{{ image.get_absolute_url }}">
                {{ image.title }}
              </a>
          </li>
       {% endfor %}
    </ol>
{% endblock %}